### PR TITLE
Routing V8: Via parameter

### PR DESCRIPTION
**Pull request by cgarde89**
This will add the parameter **via** to Routing V8

Addresses issue [#46 ](https://github.com/Hi-Folks/milk-sdk-php/issues/46)

### CODE REVIEW

**Comment by roberto-butti** [comment]
Ehy @cgarde89  thank you! great implementation!
In Routing V8 we achieved 100% full coverage.
Would you like to add also test for via parameter ?
You could take a look to  tests/Here/RestApi/RoutingV8Test.php file , testBasicRouting() method.
Let me know if you want to add it.

**Comment by cgarde89** [comment]
Ups! my bad.
I'm going to write and commit the test for via parameter.

**Comment by roberto-butti** [comment]
@cgarde89  i see your additional commit. Is it completed on your side ?

**Comment by cgarde89** [comment]
Yes, It is conpleted now

**Pull request merged**
